### ISSUE TITLE
[Request]: Update Computing Accounts and Resources

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/lcls-users#36]
### Topic Description

Topics: Onboarding of users and collaborators should be updated on the "[Computing Accounts and Resources](https://lcls-users.readthedocs.io/en/latest/before/accounts/)" page to properly describe the following use cases:
- [ ] #40
- [ ] #41
- [ ] #42
- [ ] #43
- [ ] #44

### Review from Specific People?

@valmar should review this documentation.

**Comment by kmdalton** [comment]
regarding ORNL, the instructions to get a new user account are here: https://docs.olcf.ornl.gov/accounts/accounts_and_projects.html#applying-for-a-user-account

**Comment by fredericpoitevin** [comment]
Closing since it became redundant with the milestone https://github.com/lcls-users/lcls-users/milestone/1
